- 유용한 사이트: [Scipy-Lectures](https://scipy-lectures.org/)

In [2]:
from builtins import print

import numpy as np

In [13]:
a = np.array([[1,2,3,4]])
print(a.shape)
print(a)

(1, 4)
[[1 2 3 4]]


- List와 Indexing

In [14]:
A = [ 1, 'b', 'c'] # 인덱싱은 0번부터 시작
type(A)
type(A[2]) # *그 함수/리스트가 반환하는 값이나 Type을 파악하는 것이 중요하다.*

In [20]:
B = [1,2,3,4,5,6]
B[1:3] # index 1번째 이상부터 3번째 미만까지 (Slicing)
B[2:5][1] # B[2:5]의 반환형이 List이므로, 예제와 같은 구문이 가능하다.

4

- List in List

In [25]:
C = [1,2,'c',[1,3,4]]
C
C[3][0:-1] # 리스트의 원소로, 리스트가 위치할 수 있다.

[1, 3]

In [27]:
D = [[1,2,3,4],[3,[12,4,5,65], 'c',10],'a']
D[1][1][2] # 리스트 안에 리스트 안에 ... 리스트가 들어갈 수 있고, 각 리스트가 상위 리스트의 하나의 원소가 된다.

5

### Vector와 표기 단위 차이
- 수학에서 벡터의 기본 표기 단위: 열(Col) 벡터
- 코딩에서 벡터의 기본 표기 단위: 행(Row) 벡터

### Python에서 Matrix 생성하기
- \* 수식을 보고 코드로 옮길 수 있어야 한다 \* -> 수식을 해독할 수 있어야 한다.
- Python과 Numpy에서, 모든 행렬은 Array로 취급한다.

In [5]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a[1][1])

[[1 2 3]
 [4 5 6]]
5


In [12]:
a = np.array([1,2,3])
print(a.ndim) # 원소를 감싸고 있는 계층의 갯수가 최대 몇개인가? -> Numpy 배열의  차원의 수를 결정함.

b = np.array([[1,2,3]])
print(b.ndim)

1
2


In [14]:
# Numpy에서 Type 확인하기
print(b.dtype)

# Python에서 Type 확인하기
print(type(b))

int32
<class 'numpy.ndarray'>


### Python에서의 Vector
- 1-D Vector
    - Row Vector만 표현가능
- 2-D Vector
    - Row, Column Vector 표현가능

In [17]:
r1 = np.array([5,6,7]) # 행(row)벡터를 생성함
print(r1)
r2 = np.array([[5,6,7]]) # 행렬의 개념으로 생성한 행(row)벡터
print(r2)
c1 = np.array([[5],[6]]) # 열(col)벡터 생성
print(c1)

[5 6 7]
[[5 6 7]]
[[5]
 [6]]


In [6]:
# shape: Numpy에서 차원을 확인하기
x = np.array([[1,2,3],[4,5,6]])
print(x.shape)
y = np.array([[1,2],[3,4],[5,6]])
print(y.shape)
z = np.array([[1,2,3]])
print(z.shape)

(2, 3)
(3, 2)
(1, 3)


In [13]:
# T: 행렬 전치하기
x = np.array([[1,2,3],[4,5,6]])
x = x.T
print(x)

# 전치 연산자는 1차원 배열은 변환하지 못함!
a = np.array([[1,2,3]])
print(a.T)
a = np.array([4,5,6]) # 1차원 배열은 전치가 인되므로, 되도록 사용하지 말자
print(a.T)

# reshape(): 행렬의 모양을 바꿈
print(x.reshape(1,6))
print(x.reshape(1,-1)) # 2차원 배열을 반환
print(x.reshape(-1)) # 1차원 배열를 반환

[[1 4]
 [2 5]
 [3 6]]
[[1]
 [2]
 [3]]
[4 5 6]
[[1 4 2 5 3 6]]
[[1 4 2 5 3 6]]
[1 4 2 5 3 6]


In [23]:
x1 = np.array([5,6,8])
x2 = np.array([6,7,5])
x = np.array([x1, x2])
print(x)

# 벡터를 모아서 행렬 만들기
x = np.vstack([x1, x2]) # 수직으로 쌓기
print(x)
x = np.hstack([x1, x2]) # 수평으로 쌓기
print(x)

[[5 6 8]
 [6 7 5]]
[[5 6 8]
 [6 7 5]]
[5 6 8 6 7 5]


In [34]:
# 행렬 생성 함수
# ones(): 1로 채워진 행렬 생성
ones = np.ones((1,3)) # 차원을 튜플로 받아, 1로 채워진 행렬 생성
print(ones)

# zeros(): 0으로 채워진 행렬 생성
zeros = np.zeros((1,3))
print(zeros)

# arange(): range()처럼 구간 내 숫자가 채워진 행렬 생성
arange = np.arange(0,3,1.5)
print(arange)
for i in np.arange(10): # Iterater 역할도 가능
    print(i)

# linspace(): (~이상, ~미만, 몇개 생성)으로 구간 내 동일한 간격의 숫자가 채워진 행렬 생성
linspace = np.linspace(0,4,2)
print(linspace)

[[1. 1. 1.]]
[[0. 0. 0.]]
[0.  1.5]
0
1
2
3
4
5
6
7
8
9
[0. 4.]


In [41]:
# 랜덤 변수 생성: np.random
# rand(): 주어진 크기만큼 0~1사이 균일분포 랜덤값 채워진 행렬 출력
rand = np.random.rand(2,4)
print(rand)
rand = 2*np.random.rand(2,4) # 0과 2사이 랜덤값을 저장
print(rand)
rand = -2*np.random.rand(2,4) # 0과 -2사이 랜덤값을 저장
print(rand)

# randn(): 주어진 크기만큼 0~1사이 정규분포(평균=0, 분산=1) 랜덤값 채워진 행렬 출력
randn = np.random.randn(2,4)
print(randn)
randn = np.sqrt(10)*np.random.randn(2,4) # 0~1사이 정규분포(평균=0, 분산=10) 랜덤값 채워진 행렬 출력
print(randn)
randn = np.random.randn(2,4)-4 # 0~1사이 정규분포(평균=-4, 분산=1) 랜덤값 채워진 행렬 출력
print(randn)

[[0.6536887  0.2040218  0.25997377 0.59479989]
 [0.15787805 0.72196004 0.3340084  0.85675742]]
[[1.62612957 0.44556257 0.86117501 1.25156249]
 [1.42618789 1.15244656 0.29408548 1.06708878]]
[[-1.43980365 -0.73440772 -0.23074141 -1.72875069]
 [-1.04729578 -0.94660541 -1.51826292 -0.08148286]]
[[-2.7640036   0.6265924  -0.20724569 -0.78435519]
 [ 0.59633155 -1.13130364 -0.24898891 -1.12618473]]
[[-0.9073115  -1.00803394  4.91862338  0.91616572]
 [-0.00557399 -4.86810994  2.19484768  1.44661412]]
[[-4.30284359 -3.98181861 -3.79507261 -3.41615434]
 [-4.33404411 -4.38117156 -3.4977794  -3.69913428]]
